### ISSUE TITLE
It doesn't support hc

### ISSUE THREAD

**Issue by melsiir** [dasunpamod/sks-hc-cyh-tmt-tut-sex-unlocker#1]
I got this message when try decrypt hc file

~/sks-hc-cyh-tmt-tut-sex-unlocker $ python3 decrypt.py aka.hc
 !  Unknown file extension, defaulting to .tmt
 X  Unsupported file.

**Comment by dasunpamod** [comment]
I stop developing this tool sorry for inconvenience
